test:
	../../../util/LRAA_isoforms_to_ORFs.py --genome data/ref_genome.fa  --gtf data/LRAA.gtf --output_prefix testing --td_dir ~/GITHUB/TransDecoder/ --no_refine_starts

clean:
	rm -rf ./testing*
	rm -rf ./__chckpts
