version: 1.2
workflows:
   - name: LRAA
     subclass: WDL
     primaryDescriptorPath: /WDL/LRAA.wdl
     authors:
         - name: Brian Haas
           email: bhaas@broadinstitute.org
   - name: LRAA-cell_cluster_guided
     subclass: WDL
     primaryDescriptorPath: /WDL/LRAA-cell_cluster_guided.wdl
     authors:
         - name: Brian Haas
           email: bhaas@broadinstitute.org
   - name: LRAA-sqanti-like-reads-eval
     subclass: WDL
     primaryDescriptorPath: /WDL/LRAA-sqanti-like-reads-eval.wdl
     authors:
         - name: Brian Haas
           email: bhaas@broadinstitute.org
   - name: LRAA-sqanti-like-multi-sample-summary
     subclass: WDL
     primaryDescriptorPath: /WDL/LRAA-sqanti-like-reads-eval.summarize_mult_samples.wdl
     authors:
         - name: Brian Haas
           email: bhaas@broadinstitute.org
   - name: FSM_and_isoform_identifiability_saturation
     subclass: WDL
     primaryDescriptorPath: /WDL/FSM_and_isoform_identifiability_saturation.wdl
     authors:
         - name: Brian Haas & chatgpt
           email: bhaas@broadinstitute.org
   - name: LRAA-singlecell
     subclass: WDL
     primaryDescriptorPath: /WDL/LRAA-singlecell.wdl
     authors:
    	 - name: Brian Haas & chatgpt
           email: bhaas@broadinstitute.org
