test:


test_wdls:
	miniwdl run ../../../WDL/subwdls/Incorporate_gene_symbols.wdl  -i inputs.json -d test_incorporate_symbols_outdir --verbose --no-cache

clean:
	rm -rf ./test_incorporate_symbols_outdir
