#!/usr/bin/env python3
"""Emit the benchmarking tool registry covering every arm of the alpha grid.

One registry serves every per-sample scoring directory.  Entries whose quant
file is absent from a given raw_prog_results/ are simply not reported, so the
same registry can score a partially finished grid and the rows it does emit are
bit-identical to the rows a full pass would emit (no cross-arm coupling in the
scorer -- verified at 2, 5 and 18 arms).

Indentation is two spaces under `tools:`; the scorer's YAML loader rejects a
dedented list.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sweep_config as C  # noqa: E402

HEADER = """# EM_alpha x 3'-agreement-weighting factorial grid.
#
# Generated by testing/EM_alpha_sweep/make_registry.py -- do not hand edit.
#
# Arm naming: alpha_a<alpha with '.'->'p'>_w<1 if 3' weighting on else 0>.
# Every arm is LRAA v0.20.0 quant-only; arms differ only in --EM_alpha and
# --no_weight_reads_by_3prime_agreement.
#
# quant_id_col 1 / quant_tpm_col 3 == (transcript_id, all_reads); the scorer
# renormalizes the value column to 1e6 per file.

tools:
"""

ENTRY = """
  - name: {tool}
    family: LRAA
    quant_pattern: 'LRAA\\.{arm}\\.LRAA.*quant\\.expr$'
    quant_id_col: 1
    quant_tpm_col: 3
    color: {color}
    display: true
    venn: false
"""


def main():
    out = [HEADER]
    for a in C.ARMS:
        out.append(ENTRY.format(tool=a["tool"], arm=a["arm"], color="teal" if a["threep"] else "orange"))
    dest = sys.argv[1] if len(sys.argv) > 1 else os.path.join(C.BASE, "registry.yaml")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w") as fh:
        fh.write("".join(out))
    print(f"wrote {dest} with {len(C.ARMS)} arms")


if __name__ == "__main__":
    main()
